name: CI checks

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    if: github.event.pull_request.draft == false
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          toolchain: nightly
          override: false
      - name: Run tests
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505
        with:
          command: test
          args: --release --all --all-features

  fmt:
    if: github.event.pull_request.draft == false
    name: Rustfmt
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          toolchain: nightly
          override: false
      - run: rustup component add rustfmt --toolchain nightly
      - uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505
        with:
          toolchain: nightly
          command: fmt
          args: --all -- --check

  clippy:
    if: github.event.pull_request.draft == false
    name: Clippy
    timeout-minutes: 30
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          components: clippy
          override: false
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

